### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by digital-freak** [syncthing/syncthing-inotify#178]
I trying to use syncthing-inotify-0.8.3 on the FreeBSD 11 amd64. It works fine but not very long time.

After some time (2-7 minutes), the application runs out with an error:
```
# syncthing-inotify -home=/var/db/syncthing
[OK] 15:52:11 Watching Default Folder: /media/store3/syncthing/Sync
[OK] 15:52:11 Watching kbdx: /media/store3/syncthing/kbdx
[OK] 15:52:11 Syncthing is indexing change in default: [.stfolder]
[OK] 15:52:11 Syncthing is indexing change in xktha-95hmh: [.stfolder]
panic: runtime error: index out of range

goroutine 27 [running]:
main.watchSTEvents(0xc420114cc0, 0xc42014c000, 0x2, 0x4)
        /usr/ports/net/syncthing-inotify/work/syncthing-inotify-0.8.3/syncwatcher.go:906 +0x13f
created by main.main
        /usr/ports/net/syncthing-inotify/work/syncthing-inotify-0.8.3/syncwatcher.go:288 +0x438
```

**Comment by imsodin** [comment]
This is #154, please use an up-to-date version.
